apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
  labels:
    app: react-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: react-todo
        image: harish126/react-todo:latest
        ports:
        - containerPort: 80
