apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-app
  labels:
    app: react-todo
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo
        image: harish126/react-todo:latest  
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"

